---

version: "3.7"

services:
  go:
    command: realize start --run
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      target: build
      args:
        - GO_VERSION_TAG=${GO_VERSION_TAG}
    ports:
      - 8888:8888
      - 2345:2345
    volumes:
      - ./:/go/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    environment:
      - BACKEND_HOST=go:8888
